Repository reportportal/service-ui, pull requests merged in 2019-11, with the labels that each got.

#2167 EPMRPP-43418: React. Step level. 'History' and 'Refresh' buttons are not disabled when item is selected
  app/src/pages/inside/common/suiteTestToolbar/actionPanel/actionPanel.jsx
Labels: 5.1, bug, fixed

#2168 EPMRPP-37107: REACT. Each word in placeholder text in 'Add new dashboard' modal is written with a capital letter
  app/src/common/constants/localization.js
  app/src/components/inputs/inputTimeDateRange/inputTimeDateRange.jsx
  app/src/pages/admin/allUsersPage/modals/addUserModal/addUserModal.jsx
  app/src/pages/inside/dashboardPage/modals/addEditModal/addEditModal.jsx
Labels: 5.1, bug, fixed

#2175 EPMRPP-42815: REACT. Email notifications. 'New' label moves from the main position
  app/src/components/inputs/inputTagsSearch/inputTagsSearch.jsx
  app/src/components/inputs/inputTagsSearch/inputTagsSearch.scss
Labels: 5.1, bug, fixed

#2166 EPMRPP-43417: React. Step level. Error on updating Passed item with ' Ignore in Auto Analysis' option
  app/src/controllers/step/actionValidators.js
Labels: 5.1, bug, fixed

#2169 EPMRPP-42818: React. Project settings. Defect types. 'Reset to default colors' button is enabled for CUSTOMER, OPERATOR, MEMBER in case custom bugs exist
  app/src/common/constants/permissions.js
  app/src/common/utils/permissions/index.js
  app/src/common/utils/permissions/permissions.js
  app/src/pages/common/settingsPage/defectTypesTab/defectTypesTab.jsx
Labels: 5.1, bug, fixed

#2171 EPMRPP-42360: React. Cumulative trend chart. Pattern widget. Component health check widget. Added shared widgets displayed without data
  app/src/pages/inside/dashboardItemPage/modals/addSharedWidgetModal/addSharedWidgetModal.jsx
Labels: 5.1, bug, fixed

#2191 EPMRPP-43563. Reset to first page after merge launches.
  app/src/pages/inside/launchesPage/launchesPage.jsx
Labels: 5.1

#2181 EPMRPP-43566. Fix style for error messages in markdownViewer.
  app/src/components/main/markdown/markdownViewer/markdownViewer.scss
Labels: 5.1

#2193 EPMRPP-43904: React. Error appeared after login to RP if user was logged out from RP on 'Settings' page
  app/src/pages/common/settingsPage/defectTypesTab/defectTypesGroup.jsx
Labels: bug, fixed

#2194 EPMRPP-42843. Launches. Fix tooltip for in progress launches.
  app/src/pages/inside/common/durationBlock/durationBlock.jsx
Labels: 5.1

#2195 v5.1-clickable-area-fix
  app/src/components/widgets/multiLevelWidgets/cumulativeTrendChart/cumulativeTrendChart.jsx
  app/src/components/widgets/singleLevelWidgets/charts/failedCasesTrendChart/failedCasesTrendChart.jsx
Labels: 5.1, bug, fixed, question

#2192 EPMRPP-43903: React. Overall statistics. PUT request is sent after first clicking on the clickable area
  app/src/controllers/testItem/sagas.js
  app/src/pages/inside/common/infoLine/infoLineListView.jsx
Labels: bug, fixed

#2198 v5.1-clickable-area-fix
  app/src/components/widgets/multiLevelWidgets/cumulativeTrendChart/cumulativeTrendChart.jsx
  app/src/controllers/testItem/selectors.js
Labels: 5.1, bug, fixed

#2201 EPMRPP-38817. Fix icon overlapping in case of long value in filter field.
  app/src/components/inputs/inputFilter/inputFilter.scss
Labels: 5.1

#2172 EPMRPP-43294: React. Cumulative trend chart. No 'No data available' text for non-shared widget
  app/src/pages/inside/dashboardItemPage/widgetsGrid/widget/widget.jsx
Labels: 5.1, bug, fixed

#2204 EPMRPP-42356: React. Cumulative trend chart. Different size of fonts for statuses and checkboxes
  app/src/components/widgets/common/legend/legend.scss
  app/src/components/widgets/multiLevelWidgets/cumulativeTrendChart/legend/cumulativeChartLegend.scss
Labels: 5.1, bug, fixed

#2212 EPMRPP-44556. Add parameters on suite/test edit modal.
  app/src/pages/inside/common/modals/editItemModal/editItemModal.jsx
Labels: 5.1

#2213 EPMRPP-44267. Removed redundant requests on refresh widget with no da…
  app/src/pages/inside/dashboardItemPage/widgetsGrid/widget/widget.jsx
Labels: 5.1

#2209 EPMRPP-43963 History page. Provide access from list view & filter list view
  app/src/controllers/itemsHistory/sagas.js
  app/src/pages/inside/common/suiteTestToolbar/actionPanel/actionPanel.jsx
  app/src/pages/inside/historyPage/historyPage.jsx
  app/src/pages/inside/historyPage/historyToolbar/historyToolbar.jsx
  app/src/pages/inside/historyPage/historyView/historyControls/historyControls.scss
Labels: 5.1

#2215 EPMRPP-44650. Display full launch name on widget tooltip
  app/src/components/widgets/common/tooltip/tooltipContent/tooltipContent.scss
Labels: 5.1

#2216 EPMRPP-44582. Clickable link to users email.
  app/src/pages/admin/allUsersPage/allUsersGrid/allUsersGrid.jsx
  app/src/pages/admin/allUsersPage/allUsersGrid/allUsersGrid.scss
Labels: 5.1

#2210 EPMRPP-43961 History page. Check links
  app/src/controllers/itemsHistory/sagas.js
  app/src/controllers/testItem/selectors.js
  app/src/pages/inside/historyPage/historyPageContainer.jsx
  app/src/pages/inside/historyPage/historyView/historyControls/historyControls.jsx
  app/src/pages/inside/historyPage/historyView/historyTable/historyTable.jsx
  app/src/pages/inside/historyPage/historyView/historyTable/itemNameBlock/itemNameBlock.jsx
  app/src/pages/inside/historyPage/historyView/historyView.jsx
Labels: 5.1

#2218 EPMRPP-44677. Step view. Added test case Id on edit modal.
  app/localization/translated/be.json
  app/localization/translated/ru.json
  app/src/pages/inside/stepPage/modals/testItemDetailsModal/messages.js
  app/src/pages/inside/stepPage/modals/testItemDetailsModal/testItemDetailsModal.jsx
Labels: 5.1

#1982 EPMRPP-39299 Fix login page elements everflow
  Dockerfile-full
  Makefile
  src/main/resources/public/scss/loginPage/login.scss
Labels: 4.4

#2227 EPMRPP-44581, EPMRPP-44583. Fix filter restrictions.
  app/src/components/filterEntities/entityInputConditionalTags.jsx
  app/src/pages/admin/projectsPage/projectsToolbar/projectEntities.jsx
Labels: 5.1

#2223 EPMRPP-44553. Last Login elements shifted up from other components.
  app/src/pages/admin/allUsersPage/allUsersGrid/allUsersGrid.jsx
  app/src/pages/admin/allUsersPage/allUsersGrid/allUsersGrid.scss
Labels: 5.1

#2229 EPMRPP-44594: React: Navigation is broken in case retried element selected and user goes to any other element/item
  app/src/controllers/log/utils.js
Labels: bug, fixed

#2230 EPMRPP-44594: React: Navigation is broken in case retried element selected and user goes to any other element/item
  app/src/controllers/log/utils.js
Labels: bug, fixed

#2235 EPMRPP-44649. Widgets. Launches table. Add possibility to expand /col…
  app/src/components/widgets/singleLevelWidgets/tables/launchesTable/launchesTable.jsx
Labels: 5.1

#2234 EPMRPP-38631: Fix circular dependencies in prod build
  app/src/controllers/fetch/sagas.js
Labels: 5.1
