Repository reportportal/service-ui, pull requests merged in 2019-09, with the labels that each got.

#1988 EPMRPP-40720: [UI] WidgetWizard
  app/src/common/constants/widgetTypes.js
  app/src/common/urls.js
  app/src/pages/inside/dashboardItemPage/modals/common/img/wdgt-component-health-check-inline.svg
  app/src/pages/inside/dashboardItemPage/modals/common/widgetControls/componentHealthCheckControls/componentHealthCheckControls.jsx
  app/src/pages/inside/dashboardItemPage/modals/common/widgetControls/componentHealthCheckControls/index.js
  app/src/pages/inside/dashboardItemPage/modals/common/widgetControls/controls/attributesFieldArrayControl/attributesFieldArrayControl.jsx
  app/src/pages/inside/dashboardItemPage/modals/common/widgetControls/controls/attributesFieldArrayControl/attributesFieldArrayControl.scss
  app/src/pages/inside/dashboardItemPage/modals/common/widgetControls/controls/attributesFieldArrayControl/index.js
  app/src/pages/inside/dashboardItemPage/modals/common/widgetControls/controls/index.js
  app/src/pages/inside/dashboardItemPage/modals/common/widgetControls/controls/inputControl.jsx
  app/src/pages/inside/dashboardItemPage/modals/common/widgetControls/controls/inputControl.scss
  app/src/pages/inside/dashboardItemPage/modals/common/widgetControls/cumulativeTrendControls/cumulativeTrendControls.jsx
  app/src/pages/inside/dashboardItemPage/modals/common/widgetControls/index.js
  app/src/pages/inside/dashboardItemPage/modals/common/widgetControls/widgetControls.scss
  app/src/pages/inside/dashboardItemPage/modals/common/widgets.jsx
Labels: 5.1

#1994 EPMRPP-42016 - React. Wrong count of elements displayed on page
  app/src/controllers/pages/selectors.js
  app/src/controllers/pagination/constants.js
  app/src/controllers/pagination/index.js
Labels: bug, fixed

#1999 EPMRPP-40722 Health check widget. Groups section. Group item
  app/src/components/widgets/common/messages.js
  app/src/components/widgets/multiLevelWidgets/componentHealthCheck/groupsSection/README.md
  app/src/components/widgets/multiLevelWidgets/componentHealthCheck/groupsSection/groupItem/groupItem.jsx
  app/src/components/widgets/multiLevelWidgets/componentHealthCheck/groupsSection/groupItem/groupItem.scss
  app/src/components/widgets/multiLevelWidgets/componentHealthCheck/groupsSection/groupItem/index.js
  app/src/components/widgets/multiLevelWidgets/componentHealthCheck/groupsSection/groupsSection.jsx
  app/src/components/widgets/multiLevelWidgets/componentHealthCheck/groupsSection/groupsSection.scss
  app/src/components/widgets/multiLevelWidgets/componentHealthCheck/groupsSection/healthCheckGroupsSection.stories.jsx
  app/src/components/widgets/multiLevelWidgets/componentHealthCheck/groupsSection/index.js
  app/src/components/widgets/multiLevelWidgets/componentHealthCheck/groupsSection/propTypes.js
Labels: 5.1

#2011 EPMRPP-40726: [UI] No items case
  app/src/components/widgets/multiLevelWidgets/componentHealthCheck/componentHealthCheck.jsx
  app/src/components/widgets/multiLevelWidgets/componentHealthCheck/componentHealthCheck.scss
Labels: 5.1

#2014 EPMRPP-40727 - [UI] Clickable area, switcher, loader
  app/src/common/img/go-to-another-page-inline.svg
  app/src/components/widgets/multiLevelWidgets/componentHealthCheck/componentHealthCheck.jsx
  app/src/components/widgets/multiLevelWidgets/componentHealthCheck/groupsSection/groupItem/groupItem.jsx
  app/src/components/widgets/multiLevelWidgets/componentHealthCheck/groupsSection/groupItem/groupItem.scss
  app/src/components/widgets/multiLevelWidgets/componentHealthCheck/groupsSection/groupsSection.jsx
  app/src/controllers/testItem/constants.js
  app/src/controllers/testItem/index.js
  app/src/controllers/testItem/selectors.js
  app/src/pages/inside/dashboardItemPage/modals/common/widgetControls/componentHealthCheckControls/componentHealthCheckControls.jsx
  app/src/pages/inside/dashboardItemPage/modals/common/widgetControls/controls/attributesFieldArrayControl/attributesFieldArrayControl.jsx
  app/src/pages/inside/dashboardItemPage/modals/common/widgetControls/controls/attributesFieldArrayControl/attributesFieldArrayControl.scss
Labels: 5.1

#2017 EPMRPP-40727, EPMRPP-40724, EPMRPP-42254: code review fixing
  app/src/components/widgets/index.js
  app/src/components/widgets/multiLevelWidgets/componentHealthCheck/componentHealthCheck.jsx
  app/src/components/widgets/multiLevelWidgets/componentHealthCheck/constants.js
  app/src/components/widgets/multiLevelWidgets/componentHealthCheck/legend/componentHealthCheckBreadcrumbs.jsx
  app/src/components/widgets/multiLevelWidgets/componentHealthCheck/legend/componentHealthCheckBreadcrumbs.scss
  app/src/components/widgets/multiLevelWidgets/componentHealthCheck/legend/componentHealthCheckColorScheme.jsx
  app/src/components/widgets/utils.js
  app/src/pages/inside/dashboardItemPage/modals/common/widgetControls/controls/attributesFieldArrayControl/attributesFieldArrayControl.jsx
Labels: 5.1

#2015 EPMRPP-42159: React. Clickable area for overall statistics. Items with status 'Interrupted' are not displayed after clicking on 'Failed'
  app/src/components/widgets/singleLevelWidgets/charts/launchExecutionAndIssueStatistics/launchExecutionChart.jsx
Labels: 5.1, bug, fixed

#2018 EPMRPP-42234: React. Component health check widget. Widget information is not updated if level is removed and it was opened before editing widget
  app/src/components/widgets/multiLevelWidgets/cumulativeTrendChart/chartjsConfig.js
  app/src/components/widgets/multiLevelWidgets/cumulativeTrendChart/cumulativeTrendChart.jsx
  app/src/pages/inside/dashboardItemPage/widgetsGrid/widget/widget.jsx
Labels: 5.1, bug, fixed

#2024 EPMRPP-42275-42281-42280: React. Component health check widget. Long attribute value is not hidden in three points and tooltip, [IE11] React. Component health check widget. 'x' button is missing for the second level in edit widget modal, React. Component health check widget. Level name always displayed with 1st capital letter
  app/src/components/widgets/multiLevelWidgets/componentHealthCheck/groupsSection/groupItem/groupItem.scss
  app/src/components/widgets/multiLevelWidgets/componentHealthCheck/legend/componentHealthCheckBreadcrumbs.scss
  app/src/pages/inside/dashboardItemPage/modals/common/widgetControls/controls/attributesFieldArrayControl/attributesFieldArrayControl.scss
Labels: 5.1, bug, fixed

#2025 EPMRPP-42254: React. Component health check widget. Wrong color displayed on widget for group with 99% passing rate if 100% is specified in the WW
  app/src/components/widgets/multiLevelWidgets/componentHealthCheck/componentHealthCheck.jsx
Labels: 5.1, bug, fixed

#2030 EPMRPP-42275: React. Component health check widget. Long attribute value is not hidden in three points and tooltip
  app/src/components/widgets/multiLevelWidgets/componentHealthCheck/groupsSection/groupItem/groupItem.jsx
  app/src/components/widgets/multiLevelWidgets/componentHealthCheck/groupsSection/groupItem/groupItem.scss
Labels: 5.1, bug, fixed

#2037 EPMRPP-40416: React. Profile. Restriction for email field 256 instead of 128 symbols
  app/src/pages/inside/profilePage/modals/editPersonalInfoModal/editPersonalInfoModal.jsx
Labels: bug, fixed

#2038 EPMRPP-42258-42233: Component health check widget. Widget analyses not last 600 launches, Levels are displayed in wrong order after editing widget
  app/src/components/widgets/multiLevelWidgets/componentHealthCheck/componentHealthCheck.jsx
  app/src/pages/inside/dashboardItemPage/modals/common/widgetControls/componentHealthCheckControls/componentHealthCheckControls.jsx
Labels: 5.1, bug, fixed

#2035 EPMRPP-40414: React. Members. Restriction for search field is 256 instead of 128 symbols
  app/src/pages/common/membersPage/membersPageToolbar/membersPageToolbar.jsx
Labels: bug, fixed

#2033 EPMRPP-40750: REACT. Incorrect description for demo data
  app/src/pages/common/settingsPage/demoDataTab/demoDataTab.jsx
Labels: bug, fixed

#2044 fix after merge with develop
  app/src/common/utils/validation/commonValidators.js
  app/src/common/utils/validation/validate.js
  app/src/components/main/attributeList/editableAttribute/attributeEditor/attributeEditor.jsx
  app/src/components/widgets/multiLevelWidgets/componentHealthCheck/componentHealthCheck.jsx
  app/src/pages/inside/dashboardItemPage/modals/common/widgetControls/componentHealthCheckControls.jsx
  app/src/pages/inside/dashboardItemPage/modals/common/widgetControls/componentHealthCheckControls/index.js
  app/src/pages/inside/dashboardItemPage/modals/common/widgetControls/cumulativeTrendControls.jsx
  app/src/pages/inside/dashboardItemPage/modals/common/widgetControls/cumulativeTrendControls/index.js
Labels: 5.1, bug, fixed

#2050 EPMRPP-40732: React: 'Move to Debug' mode should not be present in 'Actions' list for user with project role=CUSTOMER
  app/src/pages/inside/launchesPage/LaunchToolbar/actionPanel/actionPanel.jsx
Labels: bug, fixed

#2040 EPMRPP-41162: React: Limitation of number of entered symbols for integration name and project in bts is not correct on Admin context
  app/src/common/utils/validation/commonValidators.js
  app/src/common/utils/validation/validate.js
  app/src/components/fields/fieldErrorHint/fieldErrorHint.jsx
  app/src/components/integrations/integrationProviders/jiraIntegration/jiraConnectionFormFields/jiraConnectionFormFields.jsx
Labels: bug, fixed

#2041 EPMRPP-38028: React: The number of retries is not on the same line with the square icons
  app/src/pages/inside/common/itemInfo/retriesCounter/retriesCounter.scss
Labels: bug, fixed

#2020 EPMRPP-41757: [UI] Grouped by failure reason: Launch name #N / LAunch name/ Applied filter from widget
  app/src/pages/inside/stepPage/modals/editDefectModals/editToInvestigateDefectModal/editToInvestigateDefectModal.jsx
  app/src/pages/inside/stepPage/modals/editDefectModals/editToInvestigateDefectModal/itemsList/itemsList.jsx
  app/src/pages/inside/stepPage/modals/editDefectModals/editToInvestigateDefectModal/itemsList/itemsListHeader/itemsListHeader.jsx
Labels: 5.1, bug, fixed

#2066 EPMRPP-41362: React. Dashboard. 'No defect' statistics is displayed on 'Launch statistics chart' widget in Timeline mode for launches with defects
  app/src/components/widgets/singleLevelWidgets/charts/launchStatisticsChart/launchStatisticsChart.jsx
Labels: bug, fixed
