Repository reportportal/service-ui, pull requests merged in 2019-10, with the labels that each got.

#2073 EPMRPP-42355: React. Pattern widget. White screen appeared after clicking on the clickable area and clicking back browser button
  app/src/components/integrations/integrationProviders/sauceLabsIntegration/utils.js
Labels: bug, fixed

#2106 EPMRPP-42450: Error on start pattern analysis manually in case the automatic analysis is set to OFF
  app/src/controllers/project/constants.js
Labels: bug, fixed

#2029 EPMRPP-42253 - React. Dashboards and widgets. Add clickable area on widgets with filters
  app/src/components/widgets/common/constants.js
  app/src/components/widgets/common/utils/index.js
  app/src/components/widgets/common/utils/utils.js
  app/src/components/widgets/multiLevelWidgets/cumulativeTrendChart/chartjsConfig.js
  app/src/components/widgets/multiLevelWidgets/cumulativeTrendChart/cumulativeDetails.jsx
  app/src/components/widgets/multiLevelWidgets/cumulativeTrendChart/cumulativeDetails.scss
  app/src/components/widgets/multiLevelWidgets/cumulativeTrendChart/cumulativeTrendChart.jsx
  app/src/components/widgets/multiLevelWidgets/mostPopularPatterns/mostPopularPatterns.jsx
  app/src/components/widgets/multiLevelWidgets/mostPopularPatterns/patternGrid/patternGrid.jsx
  app/src/components/widgets/multiLevelWidgets/mostPopularPatterns/patternGrid/patternGridColumns.jsx
  app/src/components/widgets/multiLevelWidgets/mostPopularPatterns/secondLevelPanel.jsx
  app/src/components/widgets/singleLevelWidgets/charts/failedCasesTrendChart/config/getConfig.js
  app/src/components/widgets/singleLevelWidgets/charts/failedCasesTrendChart/failedCasesTrendChart.jsx
  app/src/components/widgets/singleLevelWidgets/charts/launchStatisticsChart/constants.js
  app/src/components/widgets/singleLevelWidgets/charts/launchStatisticsChart/launchStatisticsChart.jsx
  app/src/components/widgets/singleLevelWidgets/charts/nonPassedTestCasesTrendChart/config/getConfig.js
  app/src/components/widgets/singleLevelWidgets/charts/nonPassedTestCasesTrendChart/nonPassedTestCasesTrendChart.jsx
  app/src/components/widgets/singleLevelWidgets/charts/overallStatisticsChart/defectTypeItem.jsx
  app/src/components/widgets/singleLevelWidgets/charts/overallStatisticsChart/defectTypeItem.scss
  app/src/components/widgets/singleLevelWidgets/charts/overallStatisticsChart/overallDefects.jsx
  app/src/components/widgets/singleLevelWidgets/charts/overallStatisticsChart/overallStatisticsPanel.jsx
  app/src/components/widgets/singleLevelWidgets/charts/overallStatisticsChart/progressBar.jsx
  app/src/components/widgets/singleLevelWidgets/charts/overallStatisticsChart/progressBar.scss
  app/src/components/widgets/singleLevelWidgets/charts/overallStatisticsChart/totalStatistics.jsx
  app/src/components/widgets/singleLevelWidgets/charts/passingRatePerLaunch/passingRatePerLaunch.jsx
  app/src/components/widgets/singleLevelWidgets/tables/components/launchesDetailsTable/index.js
  app/src/components/widgets/singleLevelWidgets/tables/components/launchesDetailsTable/launchesDetailsColumns.jsx
  app/src/components/widgets/singleLevelWidgets/tables/components/launchesDetailsTable/launchesDetailsColumns.scss
  app/src/components/widgets/singleLevelWidgets/tables/components/launchesDetailsTable/launchesDetailsTable.jsx
  app/src/controllers/testItem/selectors.js
Labels: 5.1

#2109 EPMRPP-42318: change request for searching attributes, add filterId, launchesLimit, isLatest parameters
  app/src/common/urls.js
  app/src/pages/inside/dashboardItemPage/modals/common/widgetControls/componentHealthCheckControls.jsx
Labels: bug, fixed

#2111 EPMRPP-40120: Widgets. not shared widget should be shown for users Non Admin
  app/src/pages/inside/dashboardItemPage/dashboardItemPage.jsx
  app/src/pages/inside/dashboardItemPage/dashboardPrintPage/dashboardPrintPage.jsx
  app/src/pages/inside/dashboardItemPage/widgetsGrid/widgetsGrid.jsx
Labels: bug, fixed

#2136 EPMRPP-42965: React: A blank page displays when user tries to update the Pattern
  app/src/pages/common/settingsPage/patternAnalysisTab/modals/renamePatternModal/renamePatternModal.jsx
Labels: bug, fixed

#2137 EPMRPP-40374: React: Based on link should be opened in a new browser tab
  app/src/pages/inside/logsPage/logItemInfo/logItemInfoTabs/logItemActivity/historyItem/historyItem.jsx
Labels: 5.1, bug, fixed

#2134 EPMRPP-42487 React. Pattern widget. Overall statistics. Cumulative trend chart. 'Latest%3Dtrue' is missing in request URL in case the widget is created for the latest launches
  app/src/components/widgets/multiLevelWidgets/cumulativeTrendChart/cumulativeTrendChart.jsx
  app/src/components/widgets/multiLevelWidgets/mostPopularPatterns/mostPopularPatterns.jsx
  app/src/components/widgets/singleLevelWidgets/charts/overallStatisticsChart/overallStatisticsPanel.jsx
Labels: 5.1

#2143 EPMRPP-43217: React. No possibility to post/link issue from 'Edit defect type' modal
  app/src/pages/inside/logsPage/logItemInfo/logItemInfo.jsx
  app/src/pages/inside/stepPage/modals/editDefectModals/editDefectModal/editDefectModal.jsx
  app/src/pages/inside/stepPage/modals/editDefectModals/editToInvestigateDefectModal/editToInvestigateDefectModal.jsx
  app/src/pages/inside/stepPage/stepPage.jsx
Labels: bug, fixed

#2124 EPMRPP-42482: React. Overall statistics (panel view). Clickable area. Wrong refines are added in case click on issue type without defects in it
  app/src/controllers/testItem/sagas.js
  app/src/controllers/testItem/utils.js
Labels: 5.1, bug, fixed

#2087 EPMRPP-33861 merge launches wrong description
  app/src/pages/inside/launchesPage/modals/launchMergeModal/launchMergeModal.jsx
Labels: 5.1

#2142 EPMRPP-43031 Move LDAP to auth integrations
  app/localization/translated/be.json
  app/localization/translated/ru.json
  app/src/common/constants/integrationNames.js
  app/src/common/img/plugins/ldap.png
  app/src/components/inputs/inputConditional/inputConditional.jsx
  app/src/components/integrations/constants.js
  app/src/components/integrations/integrationProviders/index.js
  app/src/components/integrations/integrationProviders/ldapIntegration/constants.js
  app/src/components/integrations/integrationProviders/ldapIntegration/index.js
  app/src/components/integrations/integrationProviders/ldapIntegration/ldapFormFields/index.js
  app/src/components/integrations/integrationProviders/ldapIntegration/ldapFormFields/ldapFormFields.jsx
  app/src/components/integrations/integrationProviders/ldapIntegration/ldapFormFields/ldapFormFields.scss
  app/src/components/integrations/integrationProviders/ldapIntegration/ldapSettings/index.js
  app/src/components/integrations/integrationProviders/ldapIntegration/ldapSettings/ldapSettings.jsx
  app/src/components/integrations/messages.jsx
  app/src/controllers/plugins/selectors.js
  app/src/pages/admin/pluginsPage/pluginsPage.jsx
  app/src/pages/admin/serverSettingsPage/serverSettingsTabs/authConfigurationTab/authConfigurationTab.jsx
  app/src/pages/admin/serverSettingsPage/serverSettingsTabs/authConfigurationTab/forms/index.js
  app/src/pages/admin/serverSettingsPage/serverSettingsTabs/authConfigurationTab/forms/ldapAuthForm/ldapAuthForm.jsx
  app/src/pages/admin/serverSettingsPage/serverSettingsTabs/authConfigurationTab/forms/ldapAuthForm/ldapAuthFormFields/ldapAuthFormFields.jsx
  app/src/pages/admin/serverSettingsPage/serverSettingsTabs/serverSettingsTabs.jsx
Labels: 5.1

#2148 EPMRPP-43287: [Beta] React. Cumulative trend chart. White screen appeared after navigating on custom defect type on last level of the widget
  app/src/pages/inside/common/defectTypeTooltip/defectTypeTooltip.jsx
Labels: bug, fixed

#2147 EPMRPP-42820: React. Filters. 'Save' button becomes enabled after editing shared filter for Customer, Member, Operator
  app/src/common/constants/permissions.js
  app/src/common/utils/permissions/index.js
  app/src/common/utils/permissions/permissions.js
  app/src/pages/inside/common/launchFiltersToolbar/launchFiltersToolbar.jsx
Labels: 5.1, bug, fixed

#2154 EPMRPP-42820: React. Filters. 'Save' button becomes enabled after editing shared filter for Customer, Member, Operator, after review
  app/src/common/constants/permissions.js
  app/src/common/utils/permissions/index.js
  app/src/common/utils/permissions/permissions.js
  app/src/pages/inside/common/launchFiltersToolbar/launchFiltersToolbar.jsx
Labels: bug, fixed

#2157 EPMRPP-43289 Add new widget on launches fix
  app/src/pages/inside/launchesPage/launchesPage.jsx
Labels: 5.1

#2159 EPMRPP-39640. Custom tooltip for launch and test item name.
  app/src/components/main/tooltips/tooltip/withTooltip.jsx
  app/src/pages/inside/common/itemInfo/itemInfo.jsx
  app/src/pages/inside/common/itemInfo/itemInfo.scss
Labels: 5.1

#2161 EPMRPP-43362: React. Widgets resized on desktop version after opening the same dashboard via mobile device
  app/src/pages/inside/dashboardItemPage/widgetsGrid/widgetsGrid.jsx
Labels: 5.1, bug, fixed

#2160 EPMRPP-43395 Hide extra popups on logout
  app/src/controllers/auth/sagas.js
  app/src/pages/inside/launchesPage/modals/launchMergeModal/launchMergeModal.jsx
  app/src/pages/inside/stepPage/modals/testItemDetailsModal/testItemDetailsModal.jsx
Labels: 5.1
