Repository reportportal/service-ui, pull requests merged in 2019-12, with the labels that each got.

#2231 EPMRPP-42389: Sync active project with URL in case of wrong project
  app/src/routes/routesMap.js
Labels: 5.1

#2236 EPMRPP-44594: React: Navigation is broken in case retried element selected and user goes to any other element/item
  app/src/pages/inside/logsPage/historyLine/historyLine.jsx
Labels: bug, fixed

#2250 EPMRPP-44917: React: No validation message is shown in status bar in case of attempt to un-assigned UPSA user from UPSA project
  app/src/pages/common/membersPage/membersGrid/unassignButton/unassignButton.jsx
Labels: bug, fixed

#2251 EPMRPP-41638: REACT. Log View. Incorrect visual illustration on the search bar
  app/src/pages/inside/logsPage/logsGrid/logMessageSearch/logMessageSearch.scss
Labels: 5.1, bug, fixed

#2240 EPMRPP-38631: Fix links on dashboard page
  app/src/components/widgets/singleLevelWidgets/tables/launchesTable/launchesTable.jsx
  app/src/pages/inside/dashboardItemPage/dashboardItemPage.jsx
Labels: 5.1

#2242 EPMRPP-44273. Fix widget tooltip position
  app/src/components/widgets/common/c3chart/chartContainer.jsx
  app/src/components/widgets/common/tooltip/tooltipWrapper/tooltipWrapper.scss
Labels: 5.1

#2245 EPMRPP-43830: REACT.Widgets. Project Activity panel. Incorrect illustration of the changes
  app/src/common/constants/actionTypes.js
  app/src/components/widgets/singleLevelWidgets/tables/projectActivity/activities/notifications.jsx
  app/src/components/widgets/singleLevelWidgets/tables/projectActivity/projectActivity.jsx
Labels: 5.1

#2253 EPMRPP-26004: Fix "restore path" on log page
  app/src/controllers/testItem/sagas.js
  app/src/pages/inside/logsPage/logItemInfo/logItemInfo.jsx
  app/src/pages/inside/logsPage/logToolbar/logToolbar.jsx
Labels: 5.1

#2247 EPMRPP-44552: React. Widgets. 'Switches' column in 'Flaky test cases table'. Change the sequence of displayed switches
  app/src/components/widgets/singleLevelWidgets/tables/flakyTests/flakyTests.jsx
Labels: 5.1

#2254 EPMRPP-44552: React. Widgets. 'Switches' column in 'Flaky test cases table'. Change the sequence of displayed switches, after review#2
  app/src/components/widgets/singleLevelWidgets/tables/flakyTests/flakyTests.jsx
Labels: 5.1, bug, fixed

#2238 EPMRPP-44748 History-page. History base switcher
  app/localization/translated/be.json
  app/localization/translated/ru.json
  app/src/common/urls.js
  app/src/components/widgets/multiLevelWidgets/cumulativeTrendChart/legend/cumulativeChartLegend.scss
  app/src/controllers/itemsHistory/actionCreators.js
  app/src/controllers/itemsHistory/constants.js
  app/src/controllers/itemsHistory/index.js
  app/src/controllers/itemsHistory/sagas.js
  app/src/controllers/log/sagas.js
  app/src/pages/inside/historyPage/historyPage.jsx
  app/src/pages/inside/historyPage/historyToolbar/actionPanel/compareWithFilterControl/compareWithFilterControl.scss
  app/src/pages/inside/historyPage/historyView/historyControls/historyControls.jsx
  app/src/pages/inside/historyPage/historyView/historyControls/historyControls.scss
  app/src/pages/inside/historyPage/historyView/historyTable/historyTable.jsx
  app/src/pages/inside/historyPage/historyView/historyView.jsx
  app/src/pages/outside/loginPage/socialSection/newsBlock/newsBlock.jsx
Labels: 5.1

#2268 Fix error when receiving non-semver service versions on login screen.
  app/src/pages/outside/loginPage/pageBlocks/serviceVersionsBlock/serviceVersionsBlockWithData.jsx
Labels: 5.1

#2276 EPMRPP-44966. Profile. Fix disable force update button.
  app/src/pages/inside/profilePage/personalInfoBlock/personalInfoBlock.jsx
Labels: hotfix

#2280 Change licence to Apache-2.0 in package.json
  app/package.json
Labels: 5.1

#2283 Add comparing type to filter history req
  app/src/controllers/itemsHistory/sagas.js
Labels: 5.1

#2285 EPMRPP-45186: Fix "marked" version for IE support
  app/package.json
Labels: 5.1
